version: '3.8'

services:
  web:
    build: .
    ports:
      - "8501:8501"
    environment:
      - DB_HOST=db
      - POSTGRES_DB=visionera_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=visionera_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
volumes:
  postgres_data: