events {}

http {
    server {
        listen 80;
        server_name 51-103-212-50.nip.io 51.103.212.50;
        return 301 https://51-103-212-50.nip.io$request_uri;
    }

    server {
        listen 443 ssl;
        server_name 51-103-212-50.nip.io;

        ssl_certificate /etc/letsencrypt/live/51-103-212-50.nip.io/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/51-103-212-50.nip.io/privkey.pem;

        location / {
            proxy_pass http://web:8501;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }

        # Админка БД (Adminer)
        location /adminer/ {
            proxy_pass http://adminer:8080/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}